### ISSUE TITLE
Name change LogbookKonni-1.2 to LogbookKonni_pi  for language file consistency

### ISSUE THREAD

**Issue by rgleason** [ptulp/LogbookKonni_pi#18]
Hakan has asked about changing the name to make it easier to handle language files. I do not know what this would effect.

Regarding the name change from LogbookKonni-1.2 to LogbookKonni_pi
It is easier than I thought - Do you have any suggestions? 
Easy to do   https://help.github.com/articles/renaming-a-repository/
"..., we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line:"
Renaming Github Repository https://zanshin.net/2012/04/03/renaming-github-repository/
Etiquette   https://softwareengineering.stackexchange.com/questions/188480/what-is-the-etiquette-of-renaming-an-open-source-fork

Obviously those downstream  (perhaps Pavel, Hakan and me) will need to redo our git remote
I do not know what else is involved.

**Comment by rgleason** [comment]
Well I just did it on my fork, because no one has forked my branch, so it is easy.
Now it is https://github.com/rgleason/LogbookKonni_pi

I might have to ask Kathi to re direct any link to the release section for Windows,
and then change my local repository remote.

I think it can be done safely.

**Comment by rgleason** [comment]
I just had to do the following:
1. Change my local repos     remote origin path
2. Rename my local github folder to logbookKonni_pi
3. In the Windows Github program relocate the folder by browsing and selecting.
4 .Did not have to get Kathi to redirect the website as it is 
http://opencpn.navnux.org/plugins/logbookkonni_pi/logbookkonni_pi-1.2027-ov4.2-win32.exe

**Comment by rgleason** [comment]
Peter, 
Could you try changing the name of your repository to LogbookKonni_pi as I did?
This would make it much easier for Hakan to make the Language files in the future.
Thanks.

**Comment by ptulp** [comment]
I have changed it. As I am out of country I cannot test if everything is working.

**Comment by ptulp** [comment]
Also I tried a few times to contact delatbabel to assign me as a collaborator for the  delatbabel/LogbookKonni-1.2 repository as he is the owner, but I get no response.

**Comment by delatbabel** [comment]
HI all, yes I've been unwell for a long time so I haven't been responding to messages.  I will try to make @ptulp a collaborator, stand by.

**Comment by rgleason** [comment]
Dear Del thank you. We all hope for the best. Thank you so much for all you've done! Stay in touch. Best Rick

**Comment by rgleason** [comment]
Just learned something. Git is smart. I did 
git fetch upstream/master

Then git fetched  as I had set my remote  which I had not changed (https://ptulp/logbookKonni-1.2)
Git went ahead and fetched!

I changed my remote path appropriately anyway.

**Comment by rgleason** [comment]
Peter,  I've noticed something about your Logbook repository that is different than Delababel.
Your Repos has and "Issues" TAB.  Does that mean your repository is now the main one being used?

Perhaps you should consider moving the the Opencpn.org download link to your Repository/Releases and make a Release in your repository.  It might be much easiier.

**Comment by ptulp** [comment]
Rick,

I am not the official owner of the LogbookKonni plugin.
The Issues TAB is a settings issue, I  cannot change that, Del has to do that.
I don't want to change the ownership without Del's knowledge.

Regards,
Peter

**Comment by rgleason** [comment]
Yes, I just learned that Issues is turned on locally in you repos via settings. 

I guess we just live with delabsbel repos. Thanks
